### ISSUE TITLE
value error zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by STUDENTTIANTIAN** [FlappyPeggy/DMAD#11]
Encountered an issue during the training phase in Evaluate_ped2.py.
    for video in sorted(videos_list):
        video_name = video.split('/')[-1]
        anomaly_list1 += anomaly_score_list_inv(list1[video_name])
        anomaly_list2 += anomaly_score_list_inv(list2[video_name])
        anomaly_list3 += anomaly_score_list_inv(list3[video_name])

    np.savez("./exp/ped2/log/res_list.npz", anomaly_list1, anomaly_list2, anomaly_list3, 1 - labels_list)
list1['test001'{ },'test002'{}]
list2['test001'{ },'test002'{}]
list3['test001'{ },'test002'{}]
  Why is the element test01 in the table empty

**Comment by FlappyPeggy** [comment]
check if 
```
videos_list[video_num].split('/')[-1]
```
match the keys of dict: list1...list3. The mismatch problem could be raised by different platform or wrong path.

**Comment by STUDENTTIANTIAN** [comment]
> check if
> 
> ```
> videos_list[video_num].split('/')[-1]
> ```
> 
> match the keys of dict: list1...list3. The mismatch problem could be raised by different platform or wrong path.

Thank you for your answer，I have resolved this bug, the problem lies in the dataset loading. Under this file path
".\DMAD-master\DMAD-PDM\model\utils.py"
   def setup(self):
        videos = glob.glob(os.path.join(self.dir, '*'))
        for idx, video in enumerate(sorted(videos)):
            video_name = video.split(SEP)[-1]
            self.videos[video_name] = {}
            self.videos[video_name]['path'] = video
            **self.videos[video_name]['frame'] = glob.glob(os.path.join(video, '*.jpg'))**
            self.videos[video_name]['frame'].sort()
            self.videos[video_name]['idx'] = idx
            self.videos[video_name]['length'] = len(self.videos[video_name]['frame']) 
We need to change jpg to the format of your dataset，The following code may also need to be adjusted
def __getitem__(self, index):
        video_name = self.samples[index].split(SEP)[-2]
        frame_name = int(self.samples[index].split(SEP)[-1].split('.')[-2])
        batch = []
        for i in range(self._time_step+self._num_pred):
           **/Need a check to see if the statement exceeds the upper bound/**
            image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width, self.c)
            if self.transform is not None:
                batch.append(self.transform(image))

        return np.concatenate(batch, axis=0),self.transform(np.array([[self.videos[video_name]['idx']]]))
