### ISSUE TITLE
If I want to use my own dataset for training, how should I make frame_labels_**.npy?

### ISSUE THREAD

**Issue by STUDENTTIANTIAN** [FlappyPeggy/DMAD#12]
What is the purpose of this file? I think that seems to be used to calculate some kind of result

**Comment by FlappyPeggy** [comment]
frame_labels_**.npy is convert from original label files.
If you have $A$ video clips and $B_1 \cdots B_A$ frames in each clip, concat GTs with index $[frame^1_{framelen}$ $\cdots$ $frame^1_{B_1}$ $\cdots$ $frame^A_{framelen}$ $\cdots$ $frame^A_{B_A}]$

**Comment by STUDENTTIANTIAN** [comment]
> frame_labels_**.npy is convert from original label files. If you have A video clips and B1⋯BA frames in each clip, concat GTs with index [frame11 ⋯ frameB1−framelen1 ⋯ frame1A ⋯ frameBA−framelenA]
Thank you for your reply ，i know  that B represents the total number of frames in a video clip What does framelen mean ？  If framelen is the number of frames contained in the dataset, why do we need B-framelen. Does this exclude the frames contained in the dataset?

**Comment by FlappyPeggy** [comment]
For AE use in FutureFramePred, framelen is a sub-clip of videos.
*e.g.*, if we use 4 frames as history inputs to predict the fifth one, we need to remove the first 4 GTs of a video clip.

**Comment by STUDENTTIANTIAN** [comment]
> For AE use in FutureFramePred, framelen is a sub-clip of videos. _e.g._, if we use 4 frames as history inputs to predict the fifth one, we need to remove the first 4 GTs of a video clip.

ok Thank you for your answer
