### ISSUE TITLE
Visualization of code

### ISSUE THREAD

**Issue by ATreeInMountain** [FlappyPeggy/DMAD#13]
Hello, I noticed that there is visualization in your paper, but I did not find this part in the actual code. I really need to mark the abnormal parts in the video frames when checking the test set now. Would it be convenient for you to tell me the information about this part.

**Comment by FlappyPeggy** [comment]
The visualization is manually marked, but can be created from existing code.

I suggest refering paper Appendix, [ISSUE-7](https://github.com/FlappyPeggy/DMAD/issues/7), the additional optimization on binary [mask](https://github.com/FlappyPeggy/DMAD/blob/master/DMAD-PDM/model/final_future_prediction_shanghai.py) (**L450-451**) and the object-level evaluation for [shanghaitech](https://github.com/FlappyPeggy/DMAD/blob/master/DMAD-PDM/Evaluate_shanghai.py) (**L114-126**).

With the inverted index from final anomaly score, you may want to check anomaly detection (object-level) result.

**Comment by FlappyPeggy** [comment]
Hi, ATreeInMountain~
If there are any further questions, just let me know~
