### ISSUE TITLE
Training on shanghaitech dataset

### ISSUE THREAD

**Issue by LBAMAD** [FlappyPeggy/DMAD#14]
Hello,thank you for your open-source of such great work!
However,when I generated the background images of the shanghaitech dataset,I encountered the following problem:
File "/workspace/DMAD/DMAD-PDM/Train_shanghai.py", line 57, in MNADTrain
    gen_bkg_(test_folder, "./bkg_/", )
  File "/workspace/DMAD/DMAD-PDM/utils.py", line 88, in gen_bkg_
    frame = cv2.imread(img_path).copy()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'copy'
How can I solve the problem?Hope for your reply,thank you!

**Comment by FlappyPeggy** [comment]
It seems that you forget to download the background  template for ShanghaiTech or set a wrong loading path (should be "./bkg_/").

Please check readme file and download them at: [BaiduPan](https://pan.baidu.com/s/1n9ko5szFRjdYxHGbBK0TUw) (Password:dmad) or [GoogleDrive](https://drive.google.com/drive/folders/1PlRZmTFEQ7_CsrCLP9YI83rvWuAID5DF?usp=sharing)

All files are located with the same path, you just need to download them to the Corresponding Folder and Unzip.

**Comment by FlappyPeggy** [comment]
> It seems that you forget to download the background template for ShanghaiTech or set a wrong loading path (should be "./bkg_/").
> 
> Please check readme file and download them at: [BaiduPan](https://pan.baidu.com/s/1n9ko5szFRjdYxHGbBK0TUw) (Password:dmad) or [GoogleDrive](https://drive.google.com/drive/folders/1PlRZmTFEQ7_CsrCLP9YI83rvWuAID5DF?usp=sharing)
> 
> All files are located with the same path, you just need to download them to the Corresponding Folder and Unzip.

If you want to re-generate background templates, please check if the test folder (test_folder) exists.
