### ISSUE TITLE
Can't reproduce the result on Avenue dataset reported in the paper.

### ISSUE THREAD

**Issue by LBAMAD** [FlappyPeggy/DMAD#15]
Thank you for your open source of your great work!
When I run the expriment on the Avenue dataset,I have the following problem:
After I running the Train_Avenue.py file,I get the best auc score is 81.54,which is far lower than the result reported in your paper.
Can you tell me how to reproduce the auc score of 92.8 in your paper.
Hope for your reply,tanks!

**Comment by LBAMAD** [comment]
I can reproduce the results of the ped2 and shanghai datasets, but even if the pretrained model you provided is loaded on the avenue dataset, only 81% of the AUC results are obtained. May I ask what is the reason for this? I hope to receive your reply. Thank you!

**Comment by FlappyPeggy** [comment]
avenue dataset needs extra post-processing, as DMAD could identify static anomalies where **labeled as normal in original annotation** (e.g. a bag in the bottom left corner of the first few frames)

Please run process_avenue.py to remove these static anomalies.

**Comment by LBAMAD** [comment]
> avenue dataset needs extra post-processing, as DMAD could identify static anomalies where **labeled as normal in original annotation** (e.g. a bag in the bottom left corner of the first few frames)
> 
> Please run process_avenue.py to remove these static anomalies.

I have solved the problem.Thank you!

**Comment by FlappyPeggy** [comment]
> > avenue dataset needs extra post-processing, as DMAD could identify static anomalies where **labeled as normal in original annotation** (e.g. a bag in the bottom left corner of the first few frames)
> > Please run process_avenue.py to remove these static anomalies.
> 
> I have solved the problem.Thank you!

: )

**Comment by DNGC112** [comment]
> Thank you for your open source of your great work! When I run the expriment on the Avenue dataset,I have the following problem: After I running the Train_Avenue.py file,I get the best auc score is 81.54,which is far lower than the result reported in your paper. Can you tell me how to reproduce the auc score of 92.8 in your paper. Hope for your reply,tanks!

Hello, I have encountered the same problem as you, but it has not been resolved yet. The result of running the process.exe file is Avenue res: 0 [0.2, 0.4, 0.6]. I don't understand where the problem is, can you tell me how you solved it. Thank you.

**Comment by LBAMAD** [comment]
> > Thank you for your open source of your great work! When I run the expriment on the Avenue dataset,I have the following problem: After I running the Train_Avenue.py file,I get the best auc score is 81.54,which is far lower than the result reported in your paper. Can you tell me how to reproduce the auc score of 92.8 in your paper. Hope for your reply,tanks!
> 
> Hello, I have encountered the same problem as you, but it has not been resolved yet. The result of running the process.exe file is Avenue res: 0 [0.2, 0.4, 0.6]. I don't understand where the problem is, can you tell me how you solved it. Thank you.

You may run the Train_Avenue.py first, and then run the process_avenue.py.

**Comment by yinyexingchen** [comment]
> > > Thank you for your open source of your great work! When I run the expriment on the Avenue dataset,I have the following problem: After I running the Train_Avenue.py file,I get the best auc score is 81.54,which is far lower than the result reported in your paper. Can you tell me how to reproduce the auc score of 92.8 in your paper. Hope for your reply,tanks!
> > 
> > 
> > Hello, I have encountered the same problem as you, but it has not been resolved yet. The result of running the process.exe file is Avenue res: 0 [0.2, 0.4, 0.6]. I don't understand where the problem is, can you tell me how you solved it. Thank you.
> 
> You may run the Train_Avenue.py first, and then run the process_avenue.py.

hello bro, I  have ran the Train_Avenue.py.After training 60 epochs,I should run the process_avenue.py and then run the Evaluate_Avenue.py.Is that right? Thanks in advance.

**Comment by yinyexingchen** [comment]
> avenue dataset needs extra post-processing, as DMAD could identify static anomalies where **labeled as normal in original annotation** (e.g. a bag in the bottom left corner of the first few frames)
> 
> Please run process_avenue.py to remove these static anomalies.

hello author,I ran the Train_avenue.py, but the res_list.npz file of avenue was not generated during the training process of avenue.And  I ran the process_avenue.py  getting an error withou res_list_avenue.npz file.The error was ——  File "process_avenue.py", line 138, in <module>
    arr_lists = [np.array(patch_res), np.array(offset_res)]
NameError: name 'patch_res' is not defined
So, how was the res_list_avenue.npz file generated?
