### ISSUE TITLE
Evaluating Shanghaitech

### ISSUE THREAD

**Issue by mayaghaei** [FlappyPeggy/DMAD#16]
Hi, thanks for your work and your effort in maintaining the repo. I have two questions regarding evaluation code for Shanghaitech dataset.

Specifically on the following line, https://github.com/FlappyPeggy/DMAD/blob/dedb32c74b6adb41480402cf5027c9a223e91f1a/DMAD-PDM/Evaluate_shanghai.py#L105

What does the value of 330 refer to? Because it is actually the one thing that breaks my evaluation. Without it, the evaluation code works with no error.

My second question is that I only obtain about 63% AUC on Shanghai (by removing the 330). here is the final output: 
The result of  shanghai
AUC:  63.841019524627875 %; (alpha =  [0.2, 0.4, 0.6] )

Probably I am doing something wrong, do you possibly have any hint what that might be? For the reference, I am using the given pretrained model for evaluation.

Thanks in advance,
Regards

**Comment by mayaghaei** [comment]
Also wanted to add that I know 330 is the number of videos in training set of Shanghaitech, is that the reference? In that case I do not quite understand what is the relation with evaluation/testing.

**Comment by mayaghaei** [comment]
Can I expect any response @FlappyPeggy?

**Comment by FlappyPeggy** [comment]
Hi, mayaghaei,


I sincerely apologize for the delayed response—the email system unexpectedly filtered out the notification.


You are absolutely correct: 330 means the number of videos in the training set of the ShanghaiTech dataset. 
Since DMAD requires estimating the background (each video has a corresponding background image), the background images passed during model loading include both the training and test datasets. Here, “view_idx+330” indicates that the index corresponds to the background of testing videos.


If you encountered an error, could you kindly share the log? I suspect it might be due to the background images not being loaded correctly, but I would need to analyze the logs to confirm.


Thank you for your patience and understanding.


Best regards,
wrLiu

**Comment by mayaghaei** [comment]
Thanks for your reply. Here is the error after bringing all the computation to CPU, as with computation running on GPU the real error cannot be seen. Please note that I have some additions to the original code now, so the line numbers are not exactly compatible with the repo.

`Evaluation of shanghai
  0%|                                                 | 0/40363 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "PATH/DMAD/DMAD-PDM/Evaluate_shanghai.py", line 185, in <module>
    MNADEval()
  File "PATH/DMAD/DMAD-PDM/Evaluate_shanghai.py", line 112, in MNADEval
    outputs = model.forward(imgs[:, 0:12],vidx, True)
  File "PATH/DMAD/DMAD-PDM/model/final_future_prediction_shanghai.py", line 412, in forward
    x = torch.cat([x,self.bkg[idx].detach()],dim=1)
IndexError: index 330 is out of bounds for dimension 0 with size 330`

**Comment by FlappyPeggy** [comment]
> Thanks for your reply. Here is the error after bringing all the computation to CPU, as with computation running on GPU the real error cannot be seen. Please note that I have some additions to the original code now, so the line numbers are not exactly compatible with the repo.
> 
> `Evaluation of shanghai 0%| | 0/40363 [00:00<?, ?it/s] Traceback (most recent call last): File "PATH/DMAD/DMAD-PDM/Evaluate_shanghai.py", line 185, in <module> MNADEval() File "PATH/DMAD/DMAD-PDM/Evaluate_shanghai.py", line 112, in MNADEval outputs = model.forward(imgs[:, 0:12],vidx, True) File "PATH/DMAD/DMAD-PDM/model/final_future_prediction_shanghai.py", line 412, in forward x = torch.cat([x,self.bkg[idx].detach()],dim=1) IndexError: index 330 is out of bounds for dimension 0 with size 330`

Have you download bkg_.zip to the root path (DMAD-PDM) and extract it? It seems that the background images for the test set were not loaded correctly."

**Comment by mayaghaei** [comment]
I think I have done that correctly, here is a screenshot of it:
<img width="931" alt="bikesafeai" src="https://github.com/user-attachments/assets/7f46cb7c-f458-41bf-b322-e34700b1b683">

Edit: I also debugged the code, and the images inside the "bkg" folder are loading correctly by the "utils/get_bkg" method. List of their names is also printed correctly on the console.

**Comment by FlappyPeggy** [comment]
> I think I have done that correctly, here is a screenshot of it: <img alt="bikesafeai" width="931" src="https://private-user-images.githubusercontent.com/10741281/377081332-7f46cb7c-f458-41bf-b322-e34700b1b683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMjQ1ODEsIm5iZiI6MTcyOTEyNDI4MSwicGF0aCI6Ii8xMDc0MTI4MS8zNzcwODEzMzItN2Y0NmNiN2MtZjQ1OC00MWJmLWIzMjItZTM0NzAwYjFiNjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDAwMTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NGFkZTZhY2M2NDc2YTNjMjBhMDlmNTIxMTQ3ZmI3Mjg5MGM4NGY1OTJhNGJjMmJhNGM5ZTA0ZTc0YmVjYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bFUv4_EtLhNeblwv2Zd8mzITY19S8CT5YRHka84cb1c">
> 
> Edit: I also debugged the code, and the images inside the "bkg" folder are loading correctly by the "utils/get_bkg" method. List of their names is also printed correctly on the console.

I means there are two different .zip file need to download: "bkg.zip" and **"bkg_.zip"**, where the later is for test videos

**Comment by mayaghaei** [comment]
Ah, I see. That indeed solved the issue. Thanks!

**Comment by FlappyPeggy** [comment]
：）
