### ISSUE TITLE
Avenue dataset

### ISSUE THREAD

**Issue by DNGC112** [FlappyPeggy/DMAD#17]
Hello author, when I applied the Avenue dataset for replication, were the steps taken as follows:
1. First, apply the Evaluate_ avenue. py file to generate the 'dif' folder and offset8.npy file.
2. I ran the process_avenue.py file to obtain the final AUC, but when I ran the file, the result I got was Avenue res: 0 [0.2, 0.4, 0.6].
May I ask if there is a problem with the steps I reproduced, or if there are any missing areas that need to be set? Could you please provide an answer? Thank you very much.

**Comment by FlappyPeggy** [comment]
Thank you for this issue!

I made a mistake in process_avenue.py L158: 
```
auc = roc_auc_score(y_true=m_, y_score=conf_avg(recoder_param[0] * list1 + recoder_param[1]*list2)) * 100
```

it should be:
```
best = roc_auc_score(y_true=m_, y_score=conf_avg(recoder_param[0] * list1 + recoder_param[1]*list2)) * 100
```

If the issue persists, please let me know :>

**Comment by DNGC112** [comment]
> Thank you for this issue!
> 
> I made a mistake in process_avenue.py L158:
> 
> ```
> auc = roc_auc_score(y_true=m_, y_score=conf_avg(recoder_param[0] * list1 + recoder_param[1]*list2)) * 100
> ```
> 
> it should be:
> 
> ```
> best = roc_auc_score(y_true=m_, y_score=conf_avg(recoder_param[0] * list1 + recoder_param[1]*list2)) * 100
> ```
> 
> If the issue persists, please let me know :>

The problem has been resolved, thank you very much!
