### ISSUE TITLE
Shanghaitech dataset

### ISSUE THREAD

**Issue by Sweiying** [FlappyPeggy/DMAD#18]
Hello, Author,
I hope to reproduce the Shanghaitech dataset. When I followed the link you provided, I downloaded the training set, which consists of 330 video segments. Could you please provide the number of frames per second (fps) for each video?

**Comment by FlappyPeggy** [comment]
Do you mean inference FPS? Why could this vary across different video segments?

**Comment by FlappyPeggy** [comment]
My win PC(8700K+1080Ti) is about 20FPS

**Comment by Sweiying** [comment]
> 我的 win PC（8700K+1080Ti） 约为 20FPS
Hello, thank you for your reply! I may not have expressed myself clearly before. What I meant to say is that Train_shanghai is trained on video frames, while the dataset I downloaded consists of video clips. I have read the paper "ano_pred_cvpr2018," but I couldn't find information on how to extract video frames from the video clips, especially regarding how many frames should be extracted per second.Currently I'm trying to split using 20fps

**Comment by FlappyPeggy** [comment]
Got it. Please extract all frames to align with the provided npz file (label). Also, check the preprocessing part of the MNAD repo.

**Comment by Sweiying** [comment]
The problem has been resolved, thank you very much!

**Comment by yinyexingchen** [comment]
> Do you mean inference FPS? Why could this vary across different video segments?

hello author,I reproduce your work in shanghai,but I met the error IndexError: list index out of range.I extract all frames from vedios,there are 274515 frames. I find it can not get all frames when training
