### ISSUE TITLE
TypeError: cannot unpack non-iterable numpy.float64 object

### ISSUE THREAD

**Issue by wyanb** [FlappyPeggy/DMAD#5]
You are running a VQ Version 
epoch [1/400], main_loss:0.7925, offset_loss:0.0817, vq_loss:0.0107 
Traceback (most recent call last):
File "/media/xpu107/wyb/DMAD-master/DMAD-PPDM/Train_mvtec.py", line 137, in <module> 
train(i, root_path, ckpt_path, ifgeom=i in ifgeom)
File "/media/xpu107/wyb/DMAD-master/DMAD-PPDM/Train_mvtec.py", line 120, in train
auroc_px, auroc_sp = evaluation(offset, encoder, bn, decoder, test_dataloader, device, class_, mode, ifgeom)
TypeError: cannot unpack non-iterable numpy.float64 object

Hello, I think there is no problem with your code. Do you have any suggestions for this error？

**Comment by FlappyPeggy** [comment]
Thank you very much for this issue!
I forgot to fix training code after revision.

***L120*** should only contain ONE variable: auroc = evaluation(offset, encoder, bn, decoder, test_dataloader, device, _class_, mode, ifgeom)
And $print( )$ function in ***L125*** should be: print('Auroc:{:.3f}'.format(auroc))

**Comment by wyanb** [comment]
Thanks for your reply
