### ISSUE TITLE
Question regarding localization of the anomaly in PDM

### ISSUE THREAD

**Issue by kennyvoo** [FlappyPeggy/DMAD#7]
Hi author, great work! For Surveillance Videos, may I know is there a way to locate the anomaly in PDM? (just like the anomaly map in PPDM or just to know the rough location of the anomaly(difference between reconstruction over certain threshold)).

**Comment by FlappyPeggy** [comment]
Thank you~

In *final_future_prediction_ped2.py*, for example, you need to add reduction mode for *L450-L452* to obtain error map.
*For L450 & L451:* delete *.max()* in *L151*
*For L452:* use *reduction="none"* and add *.mean(1)* 
Then the three error maps are what you need.

With additional optimization on binary mask, *e.g.* shanghaitech, you may want to check object-level localization result.
To this end, use the inverted index from final result, and render the object-level mask in *Evaluate_shanghai.py L121*.

**Comment by kennyvoo** [comment]
Thank you for your timely response.

I'm new to this subject, and I would like to seek further clarification based on the information presented in your paper. In your paper, you mentioned the application of the frame-difference method to eliminate static anomalies in the Avenue dataset, which resulted in DMAD achieving the state-of-the-art performance for that dataset.

My question is whether the absence of consideration for static anomalies as anomalies in the Avenue dataset could potentially affect the ShanghaiTech dataset in a similar way.

Additionally, when comparing DMAD, a reconstruction-based method, with other methods using external object detectors and achieving higher AUC, I'm interested in understanding the weaknesses of reconstruction-based anomaly detection. It seems that reconstruction-based methods should excel at capturing static anomalies like abandoned objects. However, could you please provide insights into the limitations of reconstruction-based anomaly detection when contrasted with methods incorporating external object detectors?

I appreciate your expertise and insights on this matter.

**Comment by FlappyPeggy** [comment]
1. Consideration for static anomalies could improve AUC on ShanghaiTech. (However, ShanghaiTech does not contain wrong labels like Avenue, and the rationality is doubted)
2. Using external detectors (*e.g.* flow, segmentation) can remove background and lead to implicit centralization hypothesis. That is, they assume that objects are the basic elements for anomaly occurrence, which improves **detection sensitivity**. In fact, there are no clear limitations to whole-frame reconstructions, but the major disadvantage is the lower sensitivity compared to detection-based methods.

**Comment by kennyvoo** [comment]
Thank you for the prompt reply!

**Comment by kennyvoo** [comment]
Hi author, if I were to use it in real time, can I use it like the following snippet? if it's over certain threshold, then anomaly is detected. It;s modified from Evaluate_shanghai.py.

```python
            img_copy = ((imgs[0, -3:]+1)* 127.5).permute(1,2,0).cpu().numpy()
            img_copy = img_copy.astype(np.uint8)
            img_copy = cv2.cvtColor(img_copy, cv2.COLOR_BGR2RGB)
            
            max3 = 0
            mask_to_draw= 0
            for k in range(len(contours)):
                if cv2.contourArea(contours[k]) > 13:
                    mask_ = cv2.drawContours(np.zeros_like(mask), contours, k, 255, -1).astype(np.float32)
                    area = mask_.sum()
                    err = (mask_ * err_map.squeeze(0).cpu().numpy()).sum() / area
                    if err > max3:
                        max3 = err
                        mask_to_draw=k
            hyp_alpha = [0.2, 0.4, 0.6]

            comb = float(latest_losses['err1']) * hyp_alpha[0] + float(latest_losses['err2_']) * hyp_alpha[1] + float(max3) * hyp_alpha[2]
            if comb>0.04: #over certain threshold indicates anomaly
                cv2.drawContours(img_copy, contours, mask_to_draw, (0, 255, 0), 1) 
                img_copy = cv2.cvtColor(img_copy.astype(np.uint8),cv2.COLOR_RGB2BGR)
                cv2.imwrite(f"./visual/img_{k}_{comb}.jpg",img_copy)

```

**Comment by FlappyPeggy** [comment]
I think you are basically correct. Just pay attention to the following issues: 
1. (major) the three value may not be normalized correctly, *i.e.* different scale;
2. we use maximum value of each error map whose location may be different;
