### ISSUE TITLE
Question about training on shanghai

### ISSUE THREAD

**Issue by ck-w-0** [FlappyPeggy/DMAD#8]
File "/home/lucy/vad/DMAD-PDM/model/utils.py", line 78, in __getitem__
    image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width, self.c)
IndexError: list index out of range

**Comment by FlappyPeggy** [comment]
check if length of self.videos[video_name]['frame'] is correct?
this may be caused by different separator in different operating system.

**Comment by ck-w-0** [comment]
> check if length of self.videos[video_name]['frame'] is correct? this may be caused by different separator in different operating system.

thx!

**Comment by yinyexingchen** [comment]
> File "/home/lucy/vad/DMAD-PDM/model/utils.py", line 78, in **getitem** image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width, self.c) IndexError: list index out of range

hello, I met the same question.How did you solve it?thanks in advance
